// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    /// <summary>Order Status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Order_status
    {
        [EnumMember(Value = "placed")]
        #pragma warning disable CS1591
        Placed,
        #pragma warning restore CS1591
        [EnumMember(Value = "approved")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
    }
}
