// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Pet.FindByStatus
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "available")]
        #pragma warning disable CS1591
        Available,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "sold")]
        #pragma warning disable CS1591
        Sold,
        #pragma warning restore CS1591
    }
}
